### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Leerensucher** [pilotso11/fc-macros#13]
Whenever I try to start fcmacros.exe I get a traceback error:

Traceback (most recent call last):
  File "fcmacros.py", line 938, in <module>
  File "fcmacros.py", line 934, in run_main
  File "fcmacros.py", line 919, in run_ui
  File "fcmacros.py", line 778, in setup_ui
  File "fcmacros.py", line 122, in get_latest_log_file
ValueError: max() arg is an empty sequence

Can anybody help, please?

**Comment by pilotso11** [comment]
It can't find your latest log file.
It's a bit dumb, so if you're E:D logs are not on your C: drive it might fail.
Its just doing:

def get_latest_log_file():
    list_of_files = glob.glob(
        f"C:\\Users\\{getpass.getuser()}\\Saved Games\\Frontier Developments\\Elite Dangerous\\Journal.*")
    return max(list_of_files, key=os.path.getmtime)

If you are running from source, you can just change that to the drive your logs are on.
It would be nice if this was smarter about finding the logs.
